version: '2'

services:

  php:
    image: registry-gitlab.eolas.fr/docker/php:5.6-fpm-smart
    container_name: test_php
    volumes:
      - .:/home/wwwroot/test
    depends_on:
      - db

  apache:
    image: registry-gitlab.eolas.fr/docker/apache:2.4-base
    container_name: test_apache
    ports:
      - "80:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/test
    depends_on:
      - php

  db:
    image: mariadb:10.0
    container_name: test_db
    environment:
      MYSQL_DATABASE: lelabobois
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - test_data:/var/lib/mysql

  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: test_phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: test_db

volumes:
  test_data:
    driver: local